XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
   XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXX
  XXXXXX
    XXXX XXXXXXXXXX
        XXXXX XXXXXX XXXX X XXXXXXXX

        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
            BBBBBBBBBB
        XXXXXXX
        XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBB BB BBBBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBBBB
        XXXXXXXX
    XXXXXX
XXXXXX
XXXXXXX
XXXXXXX